# Site settings
title: Sébastien Maret
email: sebastien.maret@univ-grenoble-alpes.fr
description: Researcher at the Institut de Planétologie et d'Astrophysique de Grenoble
author: Sébastien Maret
baseurl: ""
url: "http://www.sebastienmaret.net"
email_username: sebastien.maret@univ-grenoble-alpes.fr

# Social Profiles
mastodon_profile:   https://scholar.social/@sebastienmaret
github_username:    smaret
orcid_id:           0000-0003-1104-4554

# Build settings
theme:              jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md

