# Site settings
title: Thoughts of an Astronomer
header-img: img/home-bg.jpg
email: sebastien.maret@icloud.com
description: "Sébastien Maret homepage."
baseurl: ""
url: "http://smaret.github.io"
twitter_username: sebastienmaret
github_username:  smaret
facebook_username:  sebastienmaret

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
