# Site settings
title: Sébastien Maret
email: sebastien.maret@univ-grenoble-alpes.fr
description: Researcher at the Institut de Planétologie et d'Astrophysique de Grenoble
author: Sébastien Maret
baseurl: ""
url: "http://www.sebastienmaret.net"
email_username: sebastien.maret@univ-grenoble-alpes.fr

# Social Profiles
twitter_username:   sebastienmaret
github_username:    smaret

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
