# Site settings
title: Sébastien Maret
header-img: img/home-bg.jpg
email: sebastien.maret@icloud.com
baseurl: ""
url: "http://smaret.github.io"
twitter_username: sebastienmaret
github_username:  smaret

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
